apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: default
  labels:
    app: weblog
    env: study
spec:
  containers:
  - name: debug
    image: toshikawa/debug:latest
    command:
      - "sh"
      - "-c"
    args:
      - |
        while true
        do
          sleep5
        done